---
# create the Python venv

- name: Install required global packages
  apt:
    name:
      - python3-venv
      - python3-pip

- name: Install Python requirements file
  copy:
    src: requirements.in
    dest: "{{ install_dir }}/requirements.in"
    mode: 0644

- name: Create the virtual environment
  shell: |
    python3 -m venv venv  --system-site-packages
    . venv/bin/activate
    python -m pip install --upgrade pip pip-tools
    python -m piptools compile --upgrade requirements.in
    python -m piptools sync requirements.txt
  args:
    chdir: "{{ install_dir }}"
