---
# create the Python venv

- name: Install required global packages
  apt:
    name:
      - python3-venv
      - python3-pip

- name: Install Python requirements file
  copy:
    src: "{{ item.name }}"
    dest: "{{ install_dir }}/{{ item.name }}"
    mode: "{{ item.mode }}"
  loop:
    - name: requirements.in
      mode: 664
    - name: create_venv.sh
      mode: 775

- name: Create the virtual environment
  shell:
    cmd: "{{ install_dir }}/create_venv.sh"
    chdir: "{{ install_dir }}"
